on:
  # Triggers requests on PRs to main
  push:
    branches: [ "deployment" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Frontend Deployment
        working-directory: ./frontend
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_FRONTEND_API_TOKEN }}
      - name: Frontend Deployment
        working-directory: ./backend
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_BACKEND_API_TOKEN }}
        