on:
  # Triggers requests on PRs to main
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies and lint frontend
        working-directory: ./frontend
        run: |
          npm install
          npm run lint

      - name: Use Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install pipenv
        run: pip install pipenv
      - name: Install backend dependencies and run tests
        working-directory: ./backend
        run: |
          pipenv install
          pipenv run pytest
        env:
          PYTHONPATH: ${{ github.workspace }}/backend
          IS_TESTING: 'True'
          BACKEND_URL: ''
          FRONTEND_URL: ''
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          SECRET_KEY: 'testing'

